// FIX: Replaced placeholder content with actual constant definitions to make the file a valid module.
export const CONFIG = {
    autosaveIntervalSec: 30,
    energy: {
        regenPerSec: 1 / 120, // 1 point every 2 minutes (120s) -> 100 points in 200 mins
    },
    camera: {
        zoomSpeed: 0.1,
        minZoom: 0.3,
        maxZoom: 2.0,
    },
    world: {
        width: 2000,
        height: 1500,
        maxTrees: 100,
        maxRocks: 40,
        maxWildPlants: 50,
    },
    resourceRespawn: {
        oak_tree: 1800,
        pine_tree: 1800,
        rock: 3600,
        apple_tree: 1800,
        wild_plant: 1800,
    },
    spawn: {
        oak_trees: 38,
        pine_trees: 30,
        rocks: 30,
        wild_plants: 35,
    }
};

export const ITEM_DISPLAY_NAMES: { [key: string]: string } = {
    wood: 'Madeira', stone: 'Pedra', metal: 'Metal', ironBar: 'Barra de Ferro',
    wool: 'Lã', fabric: 'Tecido', milk: 'Leite', egg: 'Ovo',
    seedGraoBaga: 'Semente de Grão Baga', seedDoceBaga: 'Semente de Doce Baga', seedCacauBaga: 'Semente de Cacau Baga', seedCafeBaga: 'Semente de Café Baga',
    graobaga: 'Grão Baga', docebaga: 'Doce Baga', cacaubaga: 'Cacau Baga', cafebaga: 'Café Baga',
    apple: 'Maçã', apple_juice: 'Suco de Maçã',
    farinha: 'Farinha', acucar: 'Açúcar', po_cacau: 'Pó de Cacau', omelet: 'Omelete', pao: 'Pão',
    biscoito_chocolate: 'Biscoito de Chocolate', bolo_chocolate: 'Bolo de Chocolate', energetico: 'Energético',
    evolution_stone: 'Pedra da Evolução', fertilizer: 'Fertilizante', honey: 'Mel',
    fiber: 'Fibra', flower: 'Flor', clothing: 'Roupa', mushroom: 'Cogumelo',
    luz: 'Luz', bateria: 'Bateria',
    dome_fossil: 'Fóssil Domo', helix_fossil: 'Fóssil Hélice', old_amber: 'Âmbar Antigo',
    jaw_fossil: 'Fóssil da Mandíbula', sail_fossil: 'Fóssil da Barbatana', cover_fossil: 'Fóssil da Carapaça', plume_fossil: 'Fóssil da Pluma', skull_fossil: 'Fóssil do Crânio', armor_fossil: 'Fóssil da Armadura', root_fossil: 'Fóssil da Raiz', claw_fossil: 'Fóssil da Garra',
};

export const ITEM_ICONS: { [key: string]: string } = {
    wood: '🌳', stone: '⚫', metal: '⚙️', ironBar: '🔩', wool: '🐑', fabric: '🧵', milk: '🥛', egg: '🥚',
    seedGraoBaga: '🍋', seedDoceBaga: '🍒', seedCacauBaga: '🥥', seedCafeBaga: '🫘',
    graobaga: '🌾', docebaga: '🍓', cacaubaga: '🟤', cafebaga: '☕',
    apple: '🍎', apple_juice: '🧃',
    farinha: '🥡', acucar: '🍬', po_cacau: '🍫', omelet: '🍳', pao: '🍞',
    biscoito_chocolate: '🍪', bolo_chocolate: '🎂', energetico: '⚡', evolution_stone: '💎',
    fertilizer: '🧪',
    honey: '🍯',
    fiber: '🌿', flower: '🌸', clothing: '👕',
    mushroom: '🍄',
    luz: '💡', bateria: '🔋',
    dome_fossil: '🐚', helix_fossil: '🌀', old_amber: '🏺',
    jaw_fossil: '🦷', sail_fossil: '⛵', cover_fossil: '🐢', plume_fossil: '🪶', skull_fossil: '💀', armor_fossil: '🛡️', root_fossil: '🌱', claw_fossil: '🦞',
};


export const RECIPES: { processing: any[], cooking: any[] } = {
    processing: [
        { id: 'iron_bar', name: 'Barra de Ferro', input: { metal: 2 }, output: { ironBar: 1 } },
        { id: 'bateria', name: 'Bateria', input: { ironBar: 1, luz: 1 }, output: { bateria: 1 } },
        { id: 'fabric', name: 'Tecido', input: { wool: 2 }, output: { fabric: 1 } },
        { id: 'clothing', name: 'Roupa', input: { fiber: 2, fabric: 1 }, output: { clothing: 1 } },
        { id: 'farinha', name: 'Farinha', input: { graobaga: 2 }, output: { farinha: 1 } },
        { id: 'acucar', name: 'Açúcar', input: { docebaga: 2 }, output: { acucar: 1 } },
        { id: 'po_cacau', name: 'Pó de Cacau', input: { cacaubaga: 2 }, output: { po_cacau: 1 } },
    ],
    cooking: [
        { id: 'omelet', name: 'Omelete', requiresStructure: 'campfire', input: { egg: 2, milk: 1 }, output: { omelet: 1 } },
        { id: 'pao', name: 'Pão', requiresStructure: 'campfire', input: { farinha: 3 }, output: { pao: 1 } },
        { id: 'biscoito_chocolate', name: 'Biscoito de Chocolate', requiresStructure: 'campfire', input: { farinha: 2, acucar: 1, po_cacau: 1, egg: 1 }, output: { biscoito_chocolate: 4 } },
        { id: 'bolo_chocolate', name: 'Bolo de Chocolate', requiresStructure: 'campfire', input: { farinha: 2, acucar: 2, po_cacau: 2, egg: 2, milk: 1 }, output: { bolo_chocolate: 1 } },
        { id: 'apple_juice', name: 'Suco de Maçã', requiresStructure: 'campfire', input: { apple: 2 }, output: { apple_juice: 1 } },
        { id: 'energetico', name: 'Energético', requiresStructure: 'campfire', input: { cafebaga: 3, acucar: 1 }, output: { energetico: 1 } },
    ]
};

export const MARKET_PRICES = {
    buy: {
        seedGraoBaga: 10,
        seedDoceBaga: 15,
        seedCacauBaga: 20,
        seedCafeBaga: 25,
        evolution_stone: 2500,
        fertilizer: 18,
        dome_fossil: 7000,
        helix_fossil: 7000,
        old_amber: 10000,
        jaw_fossil: 8000,
        sail_fossil: 8000,
        cover_fossil: 7000,
        plume_fossil: 7000,
        skull_fossil: 7000,
        armor_fossil: 7000,
        root_fossil: 7000,
        claw_fossil: 7000,
    },
    sell: {
        wood: 2,
        stone: 3,
        metal: 10,
        ironBar: 25,
        wool: 8,
        fabric: 20,
        fiber: 5,
        flower: 15,
        clothing: 40,
        milk: 12,
        egg: 5,
        graobaga: 25,
        docebaga: 35,
        cacaubaga: 50,
        cafebaga: 60,
        apple: 40,
        apple_juice: 100,
        farinha: 60,
        acucar: 85,
        po_cacau: 120,
        omelet: 60,
        pao: 200,
        biscoito_chocolate: 90,
        bolo_chocolate: 325,
        energetico: 200,
        honey: 50,
        mushroom: 15,
        luz: 75,
        bateria: 150,
    }
};

export const POKEMON_LIFESPANS: { [key: string]: number } = {
    'Abra': 90, 'Kadabra': 110, 'Alakazam': 130,
    'Bulbasaur': 100, 'Ivysaur': 120, 'Venusaur': 150, 'Oddish': 100, 'Gloom': 120, 'Vileplume': 150,
    'Charmander': 90, 'Charmeleon': 110, 'Charizard': 140,
    'Squirtle': 95, 'Wartle': 115, 'Blastoise': 145, 'Lotad': 95, 'Lombre': 115, 'Ludicolo': 145,
    'Pidgey': 50, 'Pidgeotto': 65, 'Pidgeot': 80, 'Zubat': 50, 'Golbat': 65, 'Crobat': 80,
    'Diglett': 60, 'Dugtrio': 80, 'Sandshrew': 60, 'Sandslash': 80,
    'Onix': 150, 'Steelix': 200,
    'Geodude': 70, 'Graveler': 85, 'Golem': 100, 'Rolycoly': 70, 'Carkol': 85, 'Coalossal': 100,
    'Torchic': 60, 'Combusken': 75, 'Blaziken': 90,
    'Miltank': 80,
    'Mareep': 75, 'Flaaffy': 90, 'Ampharos': 110,
    'Goldeen': 45, 'Seaking': 45,
    'Psyduck': 80,
    'Timburr': 85, 'Gurdurr': 100, 'Conkeldurr': 120, 'Pawniard': 85, 'Bisharp': 100, 'Kingambit': 120,
    'Machop': 85, 'Machoke': 100, 'Machamp': 120,
    'Gastly': 120, 'Haunter': 140, 'Gengar': 160,
    'Litwick': 110, 'Lampent': 130, 'Chandelure': 150,
    'Mankey': 70, 'Primeape': 90, 'Annihilape': 180, 'Aipom': 70, 'Ambipom': 90,
    'Tauros': 100, 'Magikarp': 40, 'Gyarados': 250,
    'Bouffalant': 100,
    'Combee': 30, 'Vespiquen': 30,
    'Teddiursa': 80, 'Ursaring': 100,
    'Rattata': 40, 'Raticate': 60,
    'Meowth': 85, 'Persian': 105,
    'Growlithe': 90, 'Arcanine': 110,
    'Ekans': 50, 'Arbok': 70,
    'Spearow': 45, 'Fearow': 65,
    'Scyther': 100, 'Scizor': 150,
    'Munchlax': 120, 'Snorlax': 250,
    'Lapras': 200,
    'Foongus': 50, 'Amoonguss': 70, 'Paras': 50, 'Parasect': 70,
    'Pichu': 60, 'Pikachu': 80, 'Raichu': 100,
    'Sunkern': 50, 'Sunflora': 70,
    'Happiny': 80, 'Chansey': 120, 'Blissey': 150,
    'Omanyte': 200, 'Omastar': 250,
    'Kabuto': 200, 'Kabutops': 250,
    'Aerodactyl': 300,
    'Tyrunt': 200, 'Tyrantrum': 250,
    'Amaura': 200, 'Aurorus': 250,
    'Tirtouga': 200, 'Carracosta': 250,
    'Archen': 200, 'Archeops': 250,
    'Cranidos': 200, 'Rampardos': 250,
    'Shieldon': 200, 'Bastiodon': 250,
    'Lileep': 200, 'Cradily': 250,
    'Anorith': 200, 'Armaldo': 250,
    'Porygon': 200, 'Porygon2': 250, 'Porygon-Z': 300,
};

export const CRAFTING_ENERGY_COST = 5;

export const POKEMON_IDS: { [key: string]: number } = {
    'Bulbasaur': 1, 'Ivysaur': 2, 'Venusaur': 3,
    'Charmander': 4, 'Charmeleon': 5, 'Charizard': 6,
    'Squirtle': 7, 'Wartortle': 8, 'Blastoise': 9,
    'Rattata': 19, 'Raticate': 20,
    'Spearow': 21, 'Fearow': 22,
    'Ekans': 23, 'Arbok': 24,
    'Pidgey': 16, 'Pidgeotto': 17, 'Pidgeot': 18,
    'Sandshrew': 27, 'Sandslash': 28,
    'Zubat': 41, 'Golbat': 42, 'Crobat': 169,
    'Oddish': 43, 'Gloom': 44, 'Vileplume': 45,
    'Paras': 46, 'Parasect': 47,
    'Diglett': 50, 'Dugtrio': 51,
    'Meowth': 52, 'Persian': 53,
    'Psyduck': 54,
    'Growlithe': 58, 'Arcanine': 59,
    'Mankey': 56, 'Primeape': 57,
    'Abra': 63, 'Kadabra': 64, 'Alakazam': 65,
    'Geodude': 74, 'Graveler': 75, 'Golem': 76,
    'Machop': 66, 'Machoke': 67, 'Machamp': 68,
    'Gastly': 92, 'Haunter': 93, 'Gengar': 94,
    'Onix': 95,
    'Goldeen': 118, 'Seaking': 119,
    'Tauros': 128, 'Magikarp': 129, 'Gyarados': 130,
    'Lapras': 131,
    'Porygon': 137,
    'Omanyte': 138, 'Omastar': 139,
    'Kabuto': 140, 'Kabutops': 141,
    'Aerodactyl': 142,
    'Snorlax': 143,
    'Mareep': 179, 'Flaaffy': 180, 'Ampharos': 181,
    'Sunkern': 191, 'Sunflora': 192,
    'Aipom': 190, 'Ambipom': 424,
    'Teddiursa': 216, 'Ursaring': 217,
    'Steelix': 208,
    'Scizor': 212,
    'Porygon2': 233,
    'Miltank': 241,
    'Torchic': 255, 'Combusken': 256, 'Blaziken': 257,
    'Lotad': 270, 'Lombre': 271, 'Ludicolo': 272,
    'Lileep': 345, 'Cradily': 346,
    'Anorith': 347, 'Armaldo': 348,
    'Combee': 415, 'Vespiquen': 416,
    'Cranidos': 408, 'Rampardos': 409,
    'Shieldon': 410, 'Bastiodon': 411,
    'Porygon-Z': 474,
    'Timburr': 532, 'Gurdurr': 533, 'Conkeldurr': 534,
    'Tirtouga': 564, 'Carracosta': 565,
    'Archen': 566, 'Archeops': 567,
    'Bouffalant': 626,
    'Litwick': 607, 'Lampent': 608, 'Chandelure': 609,
    'Pawniard': 624, 'Bisharp': 625, 'Kingambit': 983,
    'Tyrunt': 696, 'Tyrantrum': 697,
    'Amaura': 698, 'Aurorus': 699,
    'Annihilape': 979,
    'Rolycoly': 837, 'Carkol': 838, 'Coalossal': 839,
    'Scyther': 123,
    'Munchlax': 446,
    'Foongus': 590,
    'Amoonguss': 591,
    'Pichu': 172, 'Pikachu': 25, 'Raichu': 26,
    'Happiny': 440, 'Chansey': 113, 'Blissey': 242,
};

export const POKEMON_CAPACITY: { [key: string]: number } = {
    stable: 2,
    coop: 4,
    mine: 2,
    lake: 4,
    farm_area: 3,
    pokemon_gym: 6,
    laboratory: 4,
};

export const POKEMON_DRAW_COLORS: { [key: string]: string } = {
    'Bulbasaur': '#78c850', 'Ivysaur': '#78c850', 'Venusaur': '#78c850',
    'Charmander': '#f08030', 'Charmeleon': '#f08030', 'Charizard': '#f08030',
    'Squirtle': '#6890f0', 'Wartortle': '#6890f0', 'Blastoise': '#6890f0',
    'Pidgey': '#a890f0', 'Pidgeotto': '#a890f0', 'Pidgeot': '#a890f0',
    'Diglett': '#e0c068', 'Dugtrio': '#e0c068',
    'Psyduck': '#f8d030',
    'Mankey': '#c6a16b', 'Primeape': '#c6a16b', 'Aipom': '#a040a0', 'Ambipom': '#a040a0',
    'Abra': '#f8d030', 'Kadabra': '#f8d030', 'Alakazam': '#f8d030',
    'Geodude': '#b8a038', 'Graveler': '#b8a038', 'Golem': '#b8a038',
    'Gastly': '#705898', 'Haunter': '#705898', 'Gengar': '#705898',
    'Onix': '#b8a038',
    'Goldeen': '#f8d030', 'Seaking': '#f8d030',
    'Tauros': '#c6a16b', 'Magikarp': '#f08030', 'Gyarados': '#6890f0',
    'Bouffalant': '#c6a16b',
    'Combee': '#f8d030', 'Vespiquen': '#f8d030',
    'Teddiursa': '#c6a16b', 'Ursaring': '#c6a16b',
    'Mareep': '#a890f0', 'Flaaffy': '#a890f0', 'Ampharos': '#a890f0',
    'Steelix': '#b8b8d0',
    'Miltank': '#f8d030',
    'Torchic': '#f08030', 'Combusken': '#f08030', 'Blaziken': '#f08030',
    'Timburr': '#a8a878', 'Gurdurr': '#a8a878', 'Conkeldurr': '#a8a878',
    'Machop': '#a8a878', 'Machoke': '#a8a878', 'Machamp': '#a8a878',
    'Litwick': '#705898', 'Lampent': '#705898', 'Chandelure': '#705898', 'Annihilape': '#705898',
    'Rattata': '#a8a878', 'Raticate': '#a8a878',
    'Meowth': '#f8d030', 'Persian': '#f8d030',
    'Growlithe': '#f08030', 'Arcanine': '#f08030',
    'Pichu': '#f8d030', 'Pikachu': '#f8d030', 'Raichu': '#f8d030',
    'Ekans': '#a040a0', 'Arbok': '#a040a0',
    'Spearow': '#a890f0', 'Fearow': '#a890f0',
    'Sunkern': '#f8d030', 'Sunflora': '#f8d030',
    // Night Pokemon
    'Rolycoly': '#b8a038', 'Carkol': '#b8a038', 'Coalossal': '#b8a038',
    'Pawniard': '#a8a878', 'Bisharp': '#a8a878', 'Kingambit': '#a8a878',
    'Oddish': '#78c850', 'Gloom': '#78c850', 'Vileplume': '#78c850',
    'Lotad': '#6890f0', 'Lombre': '#6890f0', 'Ludicolo': '#6890f0',
    'Zubat': '#a890f0', 'Golbat': '#a890f0', 'Crobat': '#a890f0',
    'Sandshrew': '#e0c068', 'Sandslash': '#e0c068',
    'Scyther': '#78c850',
    'Scizor': '#b8b8d0',
    'Munchlax': '#385068',
    'Snorlax': '#385068',
    'Lapras': '#6890f0',
    'Foongus': '#c03030',
    'Amoonguss': '#c03030',
    'Paras': '#f08030', 'Parasect': '#f08030',
    // Fossil Pokemon
    'Omanyte': '#6890f0', 'Omastar': '#6890f0',
    'Kabuto': '#c6a16b', 'Kabutops': '#c6a16b',
    'Aerodactyl': '#a890f0',
    'Lileep': '#a040a0', 'Cradily': '#a040a0',
    'Anorith': '#b8a038', 'Armaldo': '#b8a038',
    'Cranidos': '#b8a038', 'Rampardos': '#b8a038',
    'Shieldon': '#b8b8d0', 'Bastiodon': '#b8b8d0',
    'Archen': '#f8d030', 'Archeops': '#f8d030',
    'Tirtouga': '#6890f0', 'Carracosta': '#6890f0',
    'Tyrunt': '#c6a16b', 'Tyrantrum': '#c6a16b',
    'Amaura': '#6890f0', 'Aurorus': '#6890f0',
    'Porygon': '#f85888', 'Porygon2': '#f85888', 'Porygon-Z': '#f85888',
};

export const POKEMON_EVOLUTIONS: { [key: string]: string } = {
    'Bulbasaur': 'Ivysaur', 'Ivysaur': 'Venusaur',
    'Charmander': 'Charmeleon', 'Charmeleon': 'Charizard',
    'Squirtle': 'Wartortle', 'Wartortle': 'Blastoise',
    'Pidgey': 'Pidgeotto', 'Pidgeotto': 'Pidgeot',
    'Meowth': 'Persian',
    'Growlithe': 'Arcanine',
    'Mankey': 'Primeape',
    'Aipom': 'Ambipom',
    'Abra': 'Kadabra', 'Kadabra': 'Alakazam',
    'Geodude': 'Graveler', 'Graveler': 'Golem',
    'Onix': 'Steelix',
    'Torchic': 'Combusken', 'Combusken': 'Blaziken',
    'Mareep': 'Flaaffy', 'Flaaffy': 'Ampharos',
    'Goldeen': 'Seaking',
    'Timburr': 'Gurdurr', 'Gurdurr': 'Conkeldurr',
    'Machop': 'Machoke', 'Machoke': 'Machamp',
    'Gastly': 'Haunter', 'Haunter': 'Gengar',
    'Litwick': 'Lampent', 'Lampent': 'Chandelure',
    'Combee': 'Vespiquen',
    'Teddiursa': 'Ursaring',
    'Rattata': 'Raticate',
    'Diglett': 'Dugtrio',
    'Ekans': 'Arbok',
    'Spearow': 'Fearow',
    'Sunkern': 'Sunflora',
    // Night Evolutions
    'Rolycoly': 'Carkol', 'Carkol': 'Coalossal',
    'Pawniard': 'Bisharp', 'Bisharp': 'Kingambit',
    'Oddish': 'Gloom', 'Gloom': 'Vileplume',
    'Lotad': 'Lombre', 'Lombre': 'Ludicolo',
    'Zubat': 'Golbat', 'Golbat': 'Crobat',
    'Sandshrew': 'Sandslash',
    'Scyther': 'Scizor',
    'Munchlax': 'Snorlax',
    'Foongus': 'Amoonguss', 'Paras': 'Parasect',
    'Pichu': 'Pikachu', 'Pikachu': 'Raichu',
    'Happiny': 'Chansey', 'Chansey': 'Blissey',
    // Fossil Evolutions
    'Omanyte': 'Omastar',
    'Kabuto': 'Kabutops',
    'Lileep': 'Cradily',
    'Anorith': 'Armaldo',
    'Cranidos': 'Rampardos',
    'Shieldon': 'Bastiodon',
    'Tirtouga': 'Carracosta',
    'Archen': 'Archeops',
    'Tyrunt': 'Tyrantrum',
    'Amaura': 'Aurorus',
    'Porygon': 'Porygon2', 'Porygon2': 'Porygon-Z',
};

export const POKEMON_ABILITIES: { [key: string]: any } = {
    // Daily Producers
    'Miltank': { type: 'daily_production', item: 'milk', amount: 1, chance: 0 },
    'Torchic': { type: 'daily_production', item: 'egg', amount: 1, chance: 0 },
    'Combusken': { type: 'daily_production', item: 'egg', amount: 1, chance: 0.5 },
    'Blaziken': { type: 'daily_production', item: 'egg', amount: 2, chance: 0 },
    'Mareep': { type: 'daily_production', item: 'wool', amount: 1, chance: 0 },
    'Flaaffy': { type: 'daily_production', item: 'wool', amount: 1, chance: 0.5 },
    'Ampharos': { type: 'daily_production', item: 'wool', amount: 2, chance: 0 },
    'Combee': { type: 'daily_production', item: 'honey', amount: 1, chance: 0 },
    'Vespiquen': { type: 'daily_production', item: 'honey', amount: 2, chance: 0 },
    'Foongus': { type: 'daily_production', item: 'mushroom', amount: 1, chance: 0 },
    'Amoonguss': { type: 'daily_production', item: 'mushroom', amount: 2, chance: 0 },
    'Pichu': { type: 'daily_production', item: 'luz', amount: 1, chance: 0 },
    'Pikachu': { type: 'daily_production', item: 'luz', amount: 1, chance: 0.5 },
    'Raichu': { type: 'daily_production', item: 'luz', amount: 2, chance: 0 },
    // Daily Converters
    'Charmander': { type: 'daily_conversion', from: 'metal', to: 'ironBar', amount: 1 },
    'Charmeleon': { type: 'daily_conversion', from: 'metal', to: 'ironBar', amount: 2 },
    'Charizard': { type: 'daily_conversion', from: 'metal', to: 'ironBar', amount: 3 },
    // Daily Finders (Ghosts)
    'Gastly': { type: 'daily_find', items: ['wood', 'stone'], chance: 0.15 },
    'Litwick': { type: 'daily_find', items: ['wood', 'stone'], chance: 0.15 },
    'Haunter': { type: 'daily_find', items: ['wood', 'stone'], chance: 0.20 },
    'Lampent': { type: 'daily_find', items: ['wood', 'stone'], chance: 0.20 },
    'Gengar': { type: 'daily_find', items: ['metal'], chance: 0.25 },
    'Chandelure': { type: 'daily_find', items: ['metal'], chance: 0.25 },
    'Annihilape': { type: 'daily_find', items: ['metal'], chance: 0.3 },
    'Teddiursa': { type: 'daily_find', items: ['docebaga', 'apple'], chance: 0.20 },
    'Ursaring': { type: 'daily_find', items: ['docebaga', 'apple', 'honey'], chance: 0.25 },
    // Cooldown Item Collectors
    'Bulbasaur': { type: 'harvest_plant', cooldown: 700 }, 'Oddish': { type: 'harvest_plant', cooldown: 700 },
    'Ivysaur': { type: 'harvest_plant', cooldown: 550 }, 'Gloom': { type: 'harvest_plant', cooldown: 550 },
    'Venusaur': { type: 'harvest_plant', cooldown: 400 }, 'Vileplume': { type: 'harvest_plant', cooldown: 400 },
    'Timburr': { type: 'cooldown_item', item: 'wood', cooldown: 600 }, 'Pawniard': { type: 'cooldown_item', item: 'wood', cooldown: 600 },
    'Gurdurr': { type: 'cooldown_item', item: 'wood', cooldown: 450 }, 'Bisharp': { type: 'cooldown_item', item: 'wood', cooldown: 450 },
    'Conkeldurr': { type: 'cooldown_item', item: 'wood', cooldown: 300 }, 'Kingambit': { type: 'cooldown_item', item: 'wood', cooldown: 300 },
    'Geodude': { type: 'cooldown_item', item: 'stone', cooldown: 600 }, 'Rolycoly': { type: 'cooldown_item', item: 'stone', cooldown: 600 },
    'Graveler': { type: 'cooldown_item', item: 'stone', cooldown: 480 }, 'Carkol': { type: 'cooldown_item', item: 'stone', cooldown: 480 },
    'Golem': { type: 'cooldown_item', item: 'stone', cooldown: 360 }, 'Coalossal': { type: 'cooldown_item', item: 'stone', cooldown: 360 },
    'Onix': { type: 'cooldown_item', item: 'stone', cooldown: 360 },
    'Steelix': { type: 'cooldown_item', item: 'metal', cooldown: 300 },
    'Mankey': { type: 'harvest_apple_tree', cooldown: 1800 }, 'Aipom': { type: 'harvest_apple_tree', cooldown: 1800 },
    'Primeape': { type: 'harvest_apple_tree', cooldown: 900 }, 'Ambipom': { type: 'harvest_apple_tree', cooldown: 900 },
    // Passive Income
    'Psyduck': { type: 'passive_income', rate: 60 / 86400 },
    'Goldeen': { type: 'passive_income', rate: 60 / 86400 },
    'Seaking': { type: 'passive_income', rate: 100 / 86400 },
    'Gyarados': { type: 'passive_income', rate: 500 / 86400 },
    'Meowth': { type: 'farm_protector', huntChance: 0.30, passive_income_rate: 120 / 86400 },
    'Persian': { type: 'farm_protector', huntChance: 0.50, passive_income_rate: 120 / 86400 },
    'Machop': { type: 'passive_income', rate: 80 / 86400 },
    'Machoke': { type: 'passive_income', rate: 180 / 86400 },
    'Machamp': { type: 'passive_income', rate: 400 / 86400 },
    'Abra': { type: 'passive_income', rate: 100 / 86400 },
    'Kadabra': { type: 'passive_income', rate: 300 / 86400 },
    'Alakazam': { type: 'passive_income', rate: 800 / 86400 },
    'Bouffalant': { type: 'passive_income', rate: 250 / 86400 },
    'Omanyte': { type: 'passive_income', rate: 200 / 86400 },
    'Kabuto': { type: 'passive_income', rate: 200 / 86400 },
    'Aerodactyl': { type: 'passive_income', rate: 500 / 86400 },
    'Omastar': { type: 'passive_income', rate: 450 / 86400 },
    'Kabutops': { type: 'passive_income', rate: 450 / 86400 },
    'Lileep': { type: 'passive_income', rate: 200 / 86400 },
    'Cradily': { type: 'passive_income', rate: 450 / 86400 },
    'Anorith': { type: 'passive_income', rate: 200 / 86400 },
    'Armaldo': { type: 'passive_income', rate: 450 / 86400 },
    'Cranidos': { type: 'passive_income', rate: 200 / 86400 },
    'Rampardos': { type: 'passive_income', rate: 450 / 86400 },
    'Shieldon': { type: 'passive_income', rate: 200 / 86400 },
    'Bastiodon': { type: 'passive_income', rate: 450 / 86400 },
    'Tirtouga': { type: 'passive_income', rate: 200 / 86400 },
    'Carracosta': { type: 'passive_income', rate: 450 / 86400 },
    'Archen': { type: 'passive_income', rate: 200 / 86400 },
    'Archeops': { type: 'passive_income', rate: 450 / 86400 },
    'Tyrunt': { type: 'passive_income', rate: 200 / 86400 },
    'Tyrantrum': { type: 'passive_income', rate: 450 / 86400 },
    'Amaura': { type: 'passive_income', rate: 200 / 86400 },
    'Aurorus': { type: 'passive_income', rate: 450 / 86400 },
    // Crop Workers
    'Diglett': { type: 'fertilize_crop', cooldown: 600 }, 'Sandshrew': { type: 'fertilize_crop', cooldown: 600 },
    'Dugtrio': { type: 'fertilize_crop', cooldown: 400 }, 'Sandslash': { type: 'fertilize_crop', cooldown: 400 },
    'Pidgey': { type: 'harvest_bonus', chance: 0.15 }, 'Zubat': { type: 'harvest_bonus', chance: 0.15 },
    'Pidgeotto': { type: 'harvest_bonus', chance: 0.20 }, 'Golbat': { type: 'harvest_bonus', chance: 0.20 },
    'Pidgeot': { type: 'harvest_bonus', chance: 0.25 }, 'Crobat': { type: 'harvest_bonus', chance: 0.25 },
    'Squirtle': { type: 'water_crop', cooldown: 600, bonus: 0.20 }, 'Lotad': { type: 'water_crop', cooldown: 600, bonus: 0.20 },
    'Wartortle': { type: 'water_crop', cooldown: 480, bonus: 0.25 }, 'Lombre': { type: 'water_crop', cooldown: 480, bonus: 0.25 },
    'Blastoise': { type: 'water_crop', cooldown: 360, bonus: 0.30 }, 'Ludicolo': { type: 'water_crop', cooldown: 360, bonus: 0.30 },
    'Scyther': { type: 'passive_harvest', chance: 0.5 },
    'Scizor': { type: 'passive_harvest', chance: 0.5 },
    'Sunkern': { type: 'crop_growth_accelerator', bonus: 0.15, condition: 'harsh_sunlight' },
    'Sunflora': { type: 'crop_growth_accelerator', bonus: 0.25, condition: 'harsh_sunlight' },
    // Special / Global
    'Porygon': { type: 'fossil_revival_accelerator', bonus: 0.10 },
    'Porygon2': { type: 'fossil_revival_accelerator', bonus: 0.20 },
    'Porygon-Z': { type: 'fossil_revival_accelerator', bonus: 0.30 },
    'Tauros': { type: 'miltank_breeder' },
    'Paras': { type: 'global_production_enhancer', target: ['Foongus', 'Amoonguss'], item: 'mushroom', bonus_chance: 0.10 },
    'Parasect': { type: 'global_production_enhancer', target: ['Foongus', 'Amoonguss'], item: 'mushroom', bonus_chance: 0.20 },
    // Pests & Protectors
    'Rattata': { type: 'daily_mischief', destroyChance: 0.25, evolveChance: 0.15 },
    'Raticate': { type: 'daily_mischief', destroyChance: 0.25, extraDestroyChance: 0.50 },
    'Growlithe': { type: 'farm_protector', huntChance: 0.30 },
    'Arcanine': { type: 'farm_protector', huntChance: 0.60 },
    'Ekans': { type: 'coop_pest', biteChance: 0.20, evolveChance: 0.10 },
    'Arbok': { type: 'coop_pest', biteChance: 0.20, extraBiteChance: 0.50 },
    'Spearow': { type: 'coop_protector', huntChance: 0.35 },
    'Fearow': { type: 'coop_protector', huntChance: 0.70 },
    'Munchlax': { type: 'apple_eater', cooldown: 10800 },
    'Snorlax': { type: 'passive_income', rate: 1000 / 86400 },
    'Lapras': { type: 'passive_income', rate: 1000 / 86400 },
    'Happiny': { type: 'torchic_healer', chance: 0.25 },
    'Chansey': { type: 'torchic_healer', chance: 0.50 },
    'Blissey': { type: 'torchic_healer', chance: 0.75 },
};

export const NIGHT_COUNTERPARTS: { [key: string]: { night: string, sleepHour: number } } = {
    'Geodude': { night: 'Rolycoly', sleepHour: 20 }, 'Graveler': { night: 'Carkol', sleepHour: 20 }, 'Golem': { night: 'Coalossal', sleepHour: 20 },
    'Timburr': { night: 'Pawniard', sleepHour: 20 }, 'Gurdurr': { night: 'Bisharp', sleepHour: 20 }, 'Conkeldurr': { night: 'Kingambit', sleepHour: 20 },
    'Bulbasaur': { night: 'Oddish', sleepHour: 21 }, 'Ivysaur': { night: 'Gloom', sleepHour: 21 }, 'Venusaur': { night: 'Vileplume', sleepHour: 21 },
    'Squirtle': { night: 'Lotad', sleepHour: 21 }, 'Wartortle': { night: 'Lombre', sleepHour: 21 }, 'Blastoise': { night: 'Ludicolo', sleepHour: 21 },
    'Pidgey': { night: 'Zubat', sleepHour: 22 }, 'Pidgeotto': { night: 'Golbat', sleepHour: 22 }, 'Pidgeot': { night: 'Crobat', sleepHour: 22 },
    'Diglett': { night: 'Sandshrew', sleepHour: 22 }, 'Dugtrio': { night: 'Sandslash', sleepHour: 22 },
    'Mankey': { night: 'Aipom', sleepHour: 20 }, 'Primeape': { night: 'Ambipom', sleepHour: 20 },
};

export const DAY_COUNTERPARTS: { [key: string]: string } = Object.fromEntries(
    Object.entries(NIGHT_COUNTERPARTS).map(([day, { night }]) => [night, day])
);


// This was imported but not used, defining it to avoid potential issues.
export const PINE_TREE_SPAWN_CHANCE = 0.1;
export const ALL_POKEMON_SPECIES = Object.keys(POKEMON_IDS).sort();